export const judgeSheet = {
  heading: "Evaluación",
  gateHeading: "Jurados",
  gateLede: "Solo para el jurado del GrokBot Hackathon.",
  gateUser: "Usuario",
  gatePassword: "Contraseña",
  gateSubmit: "Entrar",
  gatePending: "Entrando…",
  gateError: "No se pudo entrar. Revisa los datos e inténtalo de nuevo.",
  teamsHeading: "Equipos",
  teamsEmpty: "Aún no hay equipos registrados.",
  resultsHeading: "Resultados",
  resultsEmpty: "Todavía no hay fichas guardadas.",
  pending: "Pendiente",
  saved: "Guardada",
  membersLabel: "Integrantes",
  evaluatorLabel: "Evaluador",
  teamLabel: "Equipo",
  save: "Guardar ficha",
  saving: "Guardando…",
  savedOk: "Ficha guardada.",
  comments: "Comentarios",
  notes: "Anotaciones",
  domainLegend: "Dominio del proyecto",
  domainQuestion: "¿Demuestra comprensión real de lo entregado?",
  questionsTitle: "Preguntas sugeridas",
  totalLabel: "Puntaje total",
  logout: "Cerrar sesión",
  navTeams: "Equipos",
  navResults: "Resultados",
  questions: [
    "¿Hubo algo que la IA te sugirió y decidiste no usar? ¿Por qué?",
    "¿Cuál fue la parte más difícil, técnica o conceptualmente, y cómo la resolviste?",
    "Si tuvieras que cambiar una decisión de arquitectura, ¿cuál sería?",
    "¿Qué hace tu proyecto y cuál es su usuario/caso de uso principal?",
    "¿Qué parte implementaste tú directamente y en qué te apoyó la IA?",
    "¿De qué componente o funcionalidad están más orgullosos?",
    "¿Qué agregarían si tuvieran un día más de trabajo?",
  ],
}
